name: Run Tests On Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: employee_management_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, zip, pdo, pdo_mysql, bcmath, intl, pcntl, exif, gd, opcache, xdebug

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env.example
        run: cp .env.example .env

      - name: Generate Laravel App Key
        run: php artisan key:generate

      - name: Set up MySQL connection
        run: |
          sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=mysql/' .env
          sed -i 's/DB_DATABASE=laravel/DB_DATABASE=employee_management_test/' .env
          sed -i 's/DB_USERNAME=root/DB_USERNAME=user/' .env
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=password/' .env

      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf
          sudo ln -s /usr/bin/wkhtmltopdf /usr/local/bin/wkhtmltopdf

      - name: Create Test Database
        run: |
          php artisan migrate --env=testing

      - name: Run Tests
        run: php artisan test
